reall : clean all

all : firewall

firewall : main.o
	g++ -g -o ${BUILD_DIR}/firewall ${BUILD_DIR}/main.o -lnetfilter_queue

main.o : makeBuildFolder
	g++ -g -c -o ${BUILD_DIR}/main.o ${SOURCE_DIR}/main.cpp

makeBuildFolder : 
	mkdir -p ${BUILD_DIR}

clean :
	rm -f ${BUILD_DIR}/*
